"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Bot, Sparkles, FileText, Send, Clock, CheckCircle2,
  RefreshCw, Copy, Download, Trash2, Eye, Edit, Plus,
  Wand2, Image, Globe, Calendar, Settings, Loader2
} from "lucide-react";

type ContentType = "news" | "blog" | "social" | "email";
type ContentStatus = "draft" | "pending" | "published" | "scheduled";

interface ContentItem {
  id: string;
  title: string;
  type: ContentType;
  status: ContentStatus;
  aiGenerated: boolean;
  createdAt: string;
  publishedAt?: string;
  excerpt: string;
}

export default function ContentManagerPage() {
  const [activeTab, setActiveTab] = useState<"generate" | "library" | "schedule">("generate");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState("");
  const [contentType, setContentType] = useState<ContentType>("news");
  const [prompt, setPrompt] = useState("");
  const [tone, setTone] = useState("professional");
  const [language, setLanguage] = useState("en");

  const contentLibrary: ContentItem[] = [
    { id: "C001", title: "Kenya AI Compute Announces Major Partnership", type: "news", status: "published", aiGenerated: true, createdAt: "2025-02-05", publishedAt: "2025-02-05", excerpt: "Strategic partnership accelerates Phase 1 development..." },
    { id: "C002", title: "Why Renewable Energy Powers Our AI Future", type: "blog", status: "published", aiGenerated: true, createdAt: "2025-02-03", publishedAt: "2025-02-04", excerpt: "Kenya's geothermal advantage in AI infrastructure..." },
    { id: "C003", title: "Q1 2025 Development Update", type: "news", status: "scheduled", aiGenerated: false, createdAt: "2025-02-01", excerpt: "Progress report on construction and partnerships..." },
    { id: "C004", title: "DePIN Network Integration Launch", type: "social", status: "draft", aiGenerated: true, createdAt: "2025-01-28", excerpt: "Excited to announce our integration with..." },
    { id: "C005", title: "Investor Newsletter - February", type: "email", status: "pending", aiGenerated: true, createdAt: "2025-01-25", excerpt: "Monthly update for our valued investors..." },
  ];

  const templates = [
    { id: "t1", name: "News Article", type: "news", prompt: "Write a professional news article about [topic] for Kenya AI Compute investors and partners." },
    { id: "t2", name: "Blog Post", type: "blog", prompt: "Write an informative blog post about [topic] related to AI infrastructure and data centers." },
    { id: "t3", name: "Social Media", type: "social", prompt: "Create an engaging social media post about [topic] for LinkedIn and Twitter." },
    { id: "t4", name: "Email Newsletter", type: "email", prompt: "Write a professional email newsletter about [topic] for our mailing list." },
  ];

  const scheduledPosts = [
    { title: "Weekly Market Update", type: "social", scheduledFor: "2025-02-06 09:00", platform: "LinkedIn" },
    { title: "Team Spotlight: Engineering", type: "blog", scheduledFor: "2025-02-07 14:00", platform: "Website" },
    { title: "Investor Q1 Update", type: "email", scheduledFor: "2025-02-10 10:00", platform: "Email" },
  ];

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);

    // Simulate AI generation
    setTimeout(() => {
      setGeneratedContent(`# ${prompt}

## Overview

Kenya AI Compute is making significant strides in building Africa's premier AI infrastructure. This development represents a major milestone in our journey to bring world-class compute capabilities to the continent.

## Key Highlights

- **Strategic Partnerships**: We've secured key partnerships with leading technology providers
- **Sustainable Infrastructure**: Leveraging Kenya's 90%+ renewable energy grid
- **Global Reach**: Positioned to serve customers across Africa, Middle East, and Asia

## Looking Ahead

As we continue to execute on our roadmap, we remain committed to delivering exceptional value to our investors, partners, and customers. The future of AI in Africa starts here.

---
*Generated by AI • Kenya AI Compute*`);
      setIsGenerating(false);
    }, 2000);
  };

  const tabs = [
    { id: "generate" as const, label: "Generate", icon: Sparkles },
    { id: "library" as const, label: "Content Library", icon: FileText },
    { id: "schedule" as const, label: "Schedule", icon: Calendar },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Bot className="h-6 w-6 text-purple-500" />
            AI Content Manager
          </h1>
          <p className="text-muted-foreground">Generate, manage, and schedule content with Gemini AI</p>
        </div>
        <Badge className="bg-gradient-to-r from-purple-500 to-pink-500">
          <Sparkles className="h-3 w-3 mr-1" />
          Powered by Gemini
        </Badge>
      </div>

      {/* Stats */}
      <div className="grid gap-4 sm:grid-cols-4">
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Total Content</p>
            <p className="text-2xl font-bold">{contentLibrary.length}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">AI Generated</p>
            <p className="text-2xl font-bold">{contentLibrary.filter(c => c.aiGenerated).length}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Published</p>
            <p className="text-2xl font-bold">{contentLibrary.filter(c => c.status === "published").length}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Scheduled</p>
            <p className="text-2xl font-bold">{scheduledPosts.length}</p>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b pb-2">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-colors ${
              activeTab === tab.id ? "bg-primary text-primary-foreground" : "hover:bg-muted"
            }`}
          >
            <tab.icon className="h-4 w-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {activeTab === "generate" && (
        <div className="grid gap-6 lg:grid-cols-2">
          {/* Generator */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Wand2 className="h-5 w-5 text-purple-500" />
                Content Generator
              </CardTitle>
              <CardDescription>Create content with AI assistance</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>Content Type</Label>
                <div className="grid grid-cols-4 gap-2">
                  {["news", "blog", "social", "email"].map((type) => (
                    <button
                      key={type}
                      onClick={() => setContentType(type as ContentType)}
                      className={`px-3 py-2 text-sm rounded-lg capitalize transition-colors ${
                        contentType === type ? "bg-primary text-primary-foreground" : "border hover:bg-muted"
                      }`}
                    >
                      {type}
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-2">
                <Label>Topic / Prompt</Label>
                <textarea
                  className="w-full min-h-[100px] px-3 py-2 rounded-lg border bg-background resize-none"
                  placeholder="Describe what you want to generate..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Tone</Label>
                  <select
                    className="w-full px-3 py-2 rounded-lg border bg-background"
                    value={tone}
                    onChange={(e) => setTone(e.target.value)}
                  >
                    <option value="professional">Professional</option>
                    <option value="casual">Casual</option>
                    <option value="enthusiastic">Enthusiastic</option>
                    <option value="formal">Formal</option>
                  </select>
                </div>
                <div className="space-y-2">
                  <Label>Language</Label>
                  <select
                    className="w-full px-3 py-2 rounded-lg border bg-background"
                    value={language}
                    onChange={(e) => setLanguage(e.target.value)}
                  >
                    <option value="en">English</option>
                    <option value="zh">Chinese</option>
                    <option value="ru">Russian</option>
                  </select>
                </div>
              </div>

              <button
                onClick={handleGenerate}
                disabled={isGenerating || !prompt.trim()}
                className="w-full inline-flex items-center justify-center gap-2 px-4 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg font-medium hover:opacity-90 disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    Generate Content
                  </>
                )}
              </button>

              {/* Templates */}
              <div className="pt-4 border-t">
                <Label className="mb-3 block">Quick Templates</Label>
                <div className="grid grid-cols-2 gap-2">
                  {templates.map((template) => (
                    <button
                      key={template.id}
                      onClick={() => {
                        setContentType(template.type as ContentType);
                        setPrompt(template.prompt);
                      }}
                      className="p-3 text-left text-sm rounded-lg border hover:bg-muted"
                    >
                      <p className="font-medium">{template.name}</p>
                      <p className="text-xs text-muted-foreground truncate">{template.prompt}</p>
                    </button>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Preview */}
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>Preview</CardTitle>
                <CardDescription>Generated content preview</CardDescription>
              </div>
              {generatedContent && (
                <div className="flex gap-2">
                  <button className="p-2 hover:bg-muted rounded-lg">
                    <Copy className="h-4 w-4" />
                  </button>
                  <button className="p-2 hover:bg-muted rounded-lg">
                    <Download className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => setGeneratedContent("")}
                    className="p-2 hover:bg-muted rounded-lg text-red-500"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              )}
            </CardHeader>
            <CardContent>
              {generatedContent ? (
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <div className="p-4 rounded-lg bg-muted/50 whitespace-pre-wrap font-mono text-sm">
                    {generatedContent}
                  </div>
                  <div className="flex gap-2 mt-4">
                    <button className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 border rounded-lg hover:bg-muted">
                      <Edit className="h-4 w-4" /> Edit
                    </button>
                    <button className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90">
                      <Send className="h-4 w-4" /> Publish
                    </button>
                  </div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-12 text-center text-muted-foreground">
                  <Bot className="h-12 w-12 mb-4 opacity-20" />
                  <p>Generated content will appear here</p>
                  <p className="text-sm">Enter a topic and click Generate</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {activeTab === "library" && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Content Library</CardTitle>
              <CardDescription>All generated and created content</CardDescription>
            </div>
            <button className="inline-flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm hover:bg-primary/90">
              <Plus className="h-4 w-4" /> New Content
            </button>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left p-3 font-medium">Title</th>
                    <th className="text-left p-3 font-medium">Type</th>
                    <th className="text-left p-3 font-medium">Status</th>
                    <th className="text-left p-3 font-medium">Source</th>
                    <th className="text-left p-3 font-medium">Created</th>
                    <th className="text-left p-3 font-medium">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {contentLibrary.map((item) => (
                    <tr key={item.id} className="hover:bg-muted/30">
                      <td className="p-3">
                        <div>
                          <p className="font-medium">{item.title}</p>
                          <p className="text-sm text-muted-foreground truncate max-w-xs">{item.excerpt}</p>
                        </div>
                      </td>
                      <td className="p-3">
                        <Badge variant="outline" className="capitalize">{item.type}</Badge>
                      </td>
                      <td className="p-3">
                        <Badge variant={
                          item.status === "published" ? "default" :
                          item.status === "scheduled" ? "secondary" :
                          item.status === "pending" ? "outline" : "outline"
                        }>
                          {item.status}
                        </Badge>
                      </td>
                      <td className="p-3">
                        {item.aiGenerated ? (
                          <Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white">
                            <Bot className="h-3 w-3 mr-1" /> AI
                          </Badge>
                        ) : (
                          <Badge variant="secondary">Manual</Badge>
                        )}
                      </td>
                      <td className="p-3 text-sm text-muted-foreground">{item.createdAt}</td>
                      <td className="p-3">
                        <div className="flex gap-1">
                          <button className="p-2 hover:bg-muted rounded-lg">
                            <Eye className="h-4 w-4" />
                          </button>
                          <button className="p-2 hover:bg-muted rounded-lg">
                            <Edit className="h-4 w-4" />
                          </button>
                          <button className="p-2 hover:bg-muted rounded-lg text-red-500">
                            <Trash2 className="h-4 w-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {activeTab === "schedule" && (
        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Scheduled Posts</CardTitle>
              <CardDescription>Upcoming automated publications</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {scheduledPosts.map((post, i) => (
                  <div key={i} className="flex items-center justify-between p-4 rounded-lg border">
                    <div className="flex items-center gap-4">
                      <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center">
                        <Clock className="h-5 w-5 text-primary" />
                      </div>
                      <div>
                        <p className="font-medium">{post.title}</p>
                        <p className="text-sm text-muted-foreground">{post.scheduledFor} • {post.platform}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className="capitalize">{post.type}</Badge>
                      <button className="p-2 hover:bg-muted rounded-lg">
                        <Edit className="h-4 w-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Auto-Publishing Settings</CardTitle>
              <CardDescription>Configure automated content publishing</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between p-4 rounded-lg border">
                <div>
                  <p className="font-medium">Auto-publish to Website</p>
                  <p className="text-sm text-muted-foreground">Automatically publish approved content</p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input type="checkbox" defaultChecked className="sr-only peer" />
                  <div className="w-11 h-6 bg-muted rounded-full peer peer-checked:bg-primary after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
                </label>
              </div>

              <div className="flex items-center justify-between p-4 rounded-lg border">
                <div>
                  <p className="font-medium">Social Media Sync</p>
                  <p className="text-sm text-muted-foreground">Post to LinkedIn & Twitter</p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input type="checkbox" defaultChecked className="sr-only peer" />
                  <div className="w-11 h-6 bg-muted rounded-full peer peer-checked:bg-primary after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
                </label>
              </div>

              <div className="flex items-center justify-between p-4 rounded-lg border">
                <div>
                  <p className="font-medium">Email Newsletter</p>
                  <p className="text-sm text-muted-foreground">Send to subscriber list</p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input type="checkbox" className="sr-only peer" />
                  <div className="w-11 h-6 bg-muted rounded-full peer peer-checked:bg-primary after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
                </label>
              </div>

              <div className="p-4 rounded-lg border border-dashed">
                <div className="flex items-center gap-3">
                  <Settings className="h-5 w-5 text-muted-foreground" />
                  <div>
                    <p className="font-medium">API Integration</p>
                    <p className="text-sm text-muted-foreground">Connect Gemini API key for AI generation</p>
                  </div>
                </div>
                <Input className="mt-3" placeholder="Enter Gemini API key..." type="password" />
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
